# Generated by Django 2.2 on 2019-10-21 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helper.validators
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aids', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegNo', models.CharField(max_length=15, validators=[helper.validators.student_reg_num], verbose_name='Registration Number')),
                ('stid', models.CharField(max_length=18, unique=True, validators=[helper.validators.stid], verbose_name='Student Unique ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name(s)')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=7, verbose_name='Gender')),
                ('passport', models.FileField(blank=True, default='default.png', upload_to='passports/students', verbose_name='Passport Image')),
                ('DoR', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date of Registration')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('health_issue', models.BooleanField(default=False, verbose_name='Any Health Issue')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], default='1', max_length=10, verbose_name='Term')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('disability_details', models.CharField(default='NILL', max_length=100, verbose_name='Disability Details')),
                ('languages', models.CharField(blank=True, max_length=100, null=True, verbose_name='Language Spoken')),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Chriian', 'Christian'), ('African Tradition', 'ATR'), ('Others', 'Others')], max_length=100, null=True, verbose_name='Religion')),
                ('level', models.CharField(choices=[('JHS', 'JHS'), ('UP', 'UPPER_PRIMARY'), ('LP', 'LOWER PRIMARY'), ('PS', 'PRE_SCHOOL')], max_length=20, verbose_name='Level')),
                ('house', models.CharField(blank=True, choices=[('0NE', '0NE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('NOT ASSIGNED', 'NOT ASSIGNED')], default='NOT ASSIGNED', max_length=20, null=True, verbose_name='House/Compound')),
                ('gurdian_name', models.CharField(max_length=50, verbose_name='Guardian Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name=' Contact')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name=' Email')),
                ('father_name', models.CharField(max_length=50, verbose_name='Fathers Name')),
                ('father_hometown', models.CharField(max_length=50, verbose_name='Fathers Hometown')),
                ('father_phone', models.CharField(blank=True, max_length=30, verbose_name='Fathers Contact')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Mothers Name')),
                ('mother_phone', models.CharField(blank=True, max_length=30, verbose_name='Mothers Contact')),
                ('comment', models.TextField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(on_delete=models.SET(students.models.get_for_replace_user), to=settings.AUTH_USER_MODEL, verbose_name='Admitted By')),
                ('class_enroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aids.ClassRoom', verbose_name='Class Enroll')),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ComplainDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, verbose_name='Complain for')),
                ('details', models.TextField(verbose_name='Complain details')),
                ('stid', models.CharField(max_length=18, verbose_name='Student Unique ID')),
                ('student_name', models.CharField(max_length=70, verbose_name='Student name')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complain Desk',
                'verbose_name_plural': 'Complains Desk',
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MarksConvertions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=50, verbose_name='Exam Type')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('convert_to', models.PositiveSmallIntegerField(verbose_name='Convert score to')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marks Convertion',
                'verbose_name_plural': 'Marks Convertions',
                'ordering': ['exam_type', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TerminalExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=2, verbose_name='Term')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Raw score')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student code')),
            ],
            options={
                'verbose_name': 'Terminal Examination',
                'verbose_name_plural': 'Terminal Examinations',
                'ordering': ['term', 'raw_score', '-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentSugestionsBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(max_length=15)),
                ('body', models.TextField(verbose_name='Suggestion')),
                ('category', models.CharField(choices=[('Teachers', 'Teachers'), ('Class Room', 'Class Room'), ('Academics', 'Academic'), ('Others', 'Others')], max_length=15, verbose_name='Suggetion for')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='Sugestion Status')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('remarks', models.CharField(max_length=50, null=True, verbose_name='Sugestion remarks')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student suggestion',
                'verbose_name_plural': 'Students suggestions',
                'ordering': ['-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=15, verbose_name='Term')),
                ('raw_class_score', models.FloatField(verbose_name='Raw Class Score')),
                ('raw_exam_score', models.FloatField(verbose_name='Raw Exams Score')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'ordering': ['-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MidTermExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=2, verbose_name='Term')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Raw score')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student code')),
            ],
            options={
                'verbose_name': 'Mid-Term Examination',
                'verbose_name_plural': 'Mid-Term Examinations',
                'ordering': ['term', 'raw_score', '-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=2, verbose_name='Term')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Raw score')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student code')),
            ],
            options={
                'verbose_name': 'Class Test',
                'verbose_name_plural': 'Class Test',
                'ordering': ['term', 'raw_score', '-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=2, verbose_name='Term')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Raw score')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student code')),
            ],
            options={
                'verbose_name': 'Class Exercise',
                'verbose_name_plural': 'Class Exercises',
                'ordering': ['term', 'raw_score', '-academic_year', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassAssigment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH LANGUAGE', 'ENGLISH LANGUAGE'), ('MATHEMATICS', 'MATHEMATICS'), ('INTER SCIENCE', 'INTERGRATED SCIENCE'), ('NATURAL SCIENCE', 'NATURAL SCIENCE'), ('SOCIAL STUDIES', 'SOCIAL STUDIES'), ('INFORMATION and COMMUNICATION TECHNOLOGY', 'INFORMATION and COMMUNICATION TECHNOLOGY'), ('RELIGIOUS and MORAL EDUCATION', 'RELIGIOUS and MORAL EDUCATION'), ('BASIC DESIGN and TECHNOLOGY', 'BASIC DESIGN and TECHNOLOGY'), ('FRENCH', 'FRENCH'), ('GHANAIAN LANGUAGE and CULTURE', 'GHANAIAN LANGUAGE and CULTURE'), ('CITIZENSHIP EDUCATION', 'CITIZENSHIP EDUCATION'), ('CREATIVE ART', 'CREATIVE ART'), ('PHYSICAL EDUCATION', 'PHYSICAL EDUCATION')], max_length=50, verbose_name='Subject')),
                ('academic_year', models.CharField(choices=[('2014/2015', '2014/2015'), ('2015/2016', '2015/2016'), ('2016/2017', '2016/2017'), ('2017/2018', '2017/2018'), ('2018/2019', '2018/2019'), ('2019/2020', '2019/2020'), ('2020/2021', '2020/2021'), ('2021/2022', '2021/2022')], default='1999/1999', max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3)], max_length=2, verbose_name='Term')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Raw score')),
                ('total_marks', models.PositiveSmallIntegerField(verbose_name='Total Mark')),
                ('status', models.CharField(max_length=15, verbose_name='Performance Status')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Admission', to_field='stid', verbose_name='Student code')),
            ],
            options={
                'verbose_name': 'Class Assigment',
                'verbose_name_plural': 'Class Assigments',
                'ordering': ['term', 'raw_score', '-academic_year', '-updated', '-timestamp'],
            },
        ),
    ]
