# Generated by Django 2.2.7 on 2019-11-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsugestionsbox',
            name='suggestion_title',
        ),
    ]
