# Generated by Django 2.2 on 2019-10-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Class Name', max_length=20)),
                ('short_name', models.CharField(help_text='Enter the short name for the class', max_length=20)),
                ('numeric_name', models.CharField(help_text='Numeric Class Name', max_length=20)),
                ('class_slug', models.SlugField(help_text='Unique class name without spaces', verbose_name='Class Name Slug')),
                ('comment', models.CharField(blank=True, max_length=70, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Class Room',
                'verbose_name_plural': 'School Class Rooms',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=150)),
                ('decription', models.TextField(blank=True, verbose_name='Describtion')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Common Setting',
                'verbose_name_plural': 'School Common Settings',
                'ordering': ['name', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('Email', models.EmailField(blank=True, max_length=60, verbose_name='Email')),
                ('Message', models.TextField(max_length=50, verbose_name='Write your message ')),
                ('status', models.CharField(blank=True, max_length=15, verbose_name='Contact status')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
                'ordering': ['name', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Customiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='customize Name')),
                ('value', models.CharField(max_length=150, verbose_name='value')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Customize Status')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customization',
                'verbose_name_plural': 'Customizations',
                'ordering': ['name', '-updated', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20, verbose_name='School Registration ID')),
                ('name', models.CharField(max_length=150)),
                ('short_name', models.CharField(max_length=70)),
                ('school_motor', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('decription', models.TextField(verbose_name='Describtion')),
                ('mission', models.TextField(blank=True, verbose_name='School mission ')),
                ('vission', models.TextField(blank=True, verbose_name='School vission')),
                ('school_open_date', models.DateField(verbose_name='School Oppening Date/Year')),
                ('logo', models.FileField(blank=True, null=True, upload_to='sch-logo/', verbose_name='Passport Image')),
                ('contact', models.CharField(max_length=70)),
                ('sms_number', models.CharField(blank=True, max_length=70)),
                ('GPS_address', models.CharField(blank=True, max_length=70, verbose_name='School GPS Address')),
                ('postal_address', models.TextField(verbose_name='School Postal Address')),
                ('email', models.EmailField(max_length=254, verbose_name='School Email Address')),
                ('location', models.CharField(max_length=70)),
                ('website', models.URLField(verbose_name='School website address')),
                ('school_main_color', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Red', 'Red')], max_length=15, verbose_name='School main color')),
                ('status', models.CharField(blank=True, max_length=70, verbose_name='School Status')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Information',
                'verbose_name_plural': 'School Informations',
                'ordering': ['-updated', '-timestamp', 'school_open_date'],
            },
        ),
    ]
